" All system-wide defaults are set in $VIMRUNTIME/debian.vim and sourced by
" the call to :runtime you can find below.  If you wish to change any of those
" settings, you should do it in this file (/etc/vim/vimrc), since debian.vim
" will be overwritten everytime an upgrade of the vim packages is performed.
" It is recommended to make changes after sourcing debian.vim since it alters
" the value of the 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
" options, so any other options should be set AFTER setting 'compatible'.
"set compatible

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
if has("syntax")
  syntax on
endif

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
"set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
"if has("autocmd")
"  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
"endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
  filetype plugin indent on
endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
set ignorecase		" Do case insensitive matching
"set smartcase		" Do smart case matching
"set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
set hidden		" Hide buffers when they are abandoned
set mouse=a		" Enable mouse usage (all modes)

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

set shortmess=atI
winpos 5 5

"设置编辑器初始大小
set columns=200 lines=155

"显示行号
set number
"set go=

"autocmd InsertLeave
"autocmd InsertEnter

"设置配色方案
colorscheme ron
"colorscheme murphy

"设置状态栏
set ruler

set cmdheight=1

set scrolloff=3
set novisualbell

set foldmethod=manual

"设置背景
"set background=dark
set nocompatible

if version >= 603
    set helplang=cn
    set encoding=utf-8
endif

if (has("gui_running")) 
set guifont=Bitstream\ Vera\ Sans\ Mono\ 10 
endif
set fencs=utf-8,ucs-bom,shift-jis,gb18030,gbk,gb2312,cp936
set termencoding=utf-8
set encoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936
set fileencoding=utf-8

"设置tab键宽度
set tabstop=2
set softtabstop=2
set shiftwidth=2
set smarttab

"不自动备份
set nobackup
set autoread

"与系统共享剪贴板
set clipboard+=unnamed

"自动缩进
set autoindent
set cindent

"突出显示当前行
set cursorline

"文件为只读或者为保存时弹框
set confirm

"设置编码
set enc=utf-8
set langmenu=zh_CN.UTF-8
set helplang=cn
set laststatus=2
set linespace=2

"使退格键可用
set backspace=2

"使鼠标可用
set mouse=a
set selection=exclusive
set selectmode=mouse,key
set report=0

"括号自动配对
set showmatch

"自动格式化
set formatoptions=tcrqn

"括号自动配对
set showmatch
set matchtime=2

"查找忽略大小写
set ignorecase
set nowrapscan

"高亮显示搜索到的文本
set hlsearch
set incsearch

"开启折叠，并设置空格来开关折叠
set foldenable
set foldmethod=syntax
set foldcolumn=0
setlocal foldlevel=1
set foldclose=all
nnoremap <tab> @=((foldclosed(line('.'))<0)?'zc':'zo')<CR>
"搜索和undo时不展开设置好的折叠
set foldopen-=search
set foldopen-=undo

if has("gui_running")
"hi Cursor guifg=
hi        Cursor         guifg=grey20           guibg=#00FFD7           gui=NONE        "光标所在的字符
hi        CursorColumn                          guibg=grey20           gui=NONE        "光标所在的屏幕列
hi        CursorLine                            guibg=#666666          gui=NONE        "光标所在的屏幕行
else
hi String ctermfg=yellow cterm=bold
hi Type ctermfg=white cterm=bold
hi        Cursor         ctermfg=white            ctermbg=lightgreen        cterm=BOLD        "光标所在的字符
hi        CursorColumn                            ctermbg=black             cterm=BOLD        "光标所在的屏幕列
hi        CursorLine                              ctermbg=black             cterm=BOLD        "光标所在的屏幕行

endif




