  " don't write swapfile on most commonly used directories for NFS mounts or USB sticks
  autocmd BufNewFile,BufReadPre /media/*,/run/media/*,/mnt/* set directory=~/tmp,/var/tmp,/tmp
  " start with spec file template
  autocmd BufNewFile *.spec 0r /usr/share/vim/vimfiles/template.spec
  augroup END

if has("cscope") && filereadable("/usr/bin/cscope")
   set csprg=/usr/bin/cscope
   set csto=0
   set cst
   set nocsverb
   " add any database in current directory
   if filereadable("cscope.out")
      cs add $PWD/cscope.out
   " else add database pointed to by environment
   elseif $CSCOPE_DB != ""
      cs add $CSCOPE_DB
   endif
   set csverb
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

filetype plugin on

if &term=="xterm"
     set t_Co=8
     set t_Sb=[4%dm
     set t_Sf=[3%dm
endif

" Don't wake up system with blinking cursor:
" http://www.linuxpowertop.org/known.php
let &guicursor = &guicursor . ",a:blinkon0"


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" user .......
set completeopt=longest,menu
set tabstop=4
set softtabstop=4
set shiftwidth=2
set autoindent
set smartindent
set cindent

set nobackup
set noswapfile
set number
set mouse=v
set backspace=2
set cmdheight=1
set foldenable
set foldmethod=syntax
set foldlevel=2
set foldcolumn=1
set wildmenu
set showmatch
set matchtime=2
set ruler
set showcmd

if has("gui_running")
  colorscheme blue
endif
"colorscheme morning
colorscheme ron
"hi MatchParen ctermbg=Black ctermfg=yellow
"highlight String ctermfg=red

nmap <F5> :call CompierAndrun()<CR>
nmap <F6> :call Debug()<CR>
imap <F5> <ESC>:call CompierAndrun()<CR>
imap <F6> <ESC>:call Debug()<CR>
imap <c-k> <Up>
imap <c-u> <PageUp>
imap <c-j> <Down>
imap <c-f> <PageDown>
imap <c-h> <Left>
imap <c-f> <c-Right>
imap <c-l> <Right>
imap <c-b> <c-Left>
"imap [ []<Esc>i
"imap { {}<Esc>i
"imap ( ()<Esc>i
imap <F3> <ESC>:sh<CR>
let mapleader=";"
nmap <Leader>sh :sh<CR>
"nmap <F3> :sh<CR>
nmap <Leader>v V
imap <c-F12> <Esc>:qall<CR>
nmap <c-F12> :qall<CR>
"nmap <Esc><Esc><Esc> :nohlsearch<CR>
nmap <c-S-f> gg=GggVG:!indent -ce -npsl -br % -o %<CR>
nmap <c-j> <c-w>j
nmap <c-k> <c-w>k
nmap <c-l> <c-w>l
nmap <c-h> <c-w>h
imap <F3> <ESC>:sh<CR>
nmap <F3> :sh<CR>
imap <c-F12> <Esc>:qall<CR>
nmap <c-F12> :qall<CR>
nmap <Esc><Esc><Esc> :nohlsearch<CR>
nmap gg=G gg=GggVG:s/=/\ =\ /gc<CR>
"nmap <Leader>w <c-w> 
noremap <c-]> g]
nmap <space> za
nmap <Leader>g 1G
nmap <Leader>no :nohlsearch<CR>
nmap <Backspace> gg
"nmap <Enter> G

"
function CompierAndrun()
	:w
	if &filetype == 'c'
		 :!clear;gcc -o %< % && ./%<
	elseif &filetype == 'cxx' || &filetype == 'cpp'
		 :!clear;g++ -o %< % && ./%<
"	else return ""
	endif
endfunction

function Debug()
	:w
	if &filetype == 'c'
	:!clear;gcc -g -o %< % && gdb %<
	elseif &filetype == 'cpp'
	:!clear;g++ -g -o %< % && %<
"else return ""
	endif
endfunction

"autocmd BufNewFile *.c,*.sh,*.cpp,*.cxx exec ":call SetTitle()"
autocmd BufNewFile * normal G
function SetTitle()
	if &filetype == 'c' "|| &filetype == 'h'
		call setline(1,"\/*")
		call append(line("."),"* File Name: ".expand("%"))
		call append(line(".")+1,"* Create Date: ".strftime("%c"))
		call append(line(".")+2,"*\/")
		call append(line(".")+3,"#include <stdio.h>")
	elseif &filetype == 'cpp' || &filetype == 'cxx' 
		call setline(1,"#include <iostream>")
		call setline(2,"using ")
	endif
endfunction


set tags+=/home/tmp/tmp/src/tgas
set tags+=/home/external/Share/tiny4412/bunfly/source_code/linux-3.5/tags

