/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class person */

#ifndef _Included_person
#define _Included_person
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     person
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_person_test (JNIEnv *, jobject); 
#ifdef __cplusplus
}
#endif
#endif
