#!/bin/bash -
tmp=/home/external/sh
[ -r $tmp/check-os.sh ] && source $tmp/check-os.sh
[ $UID -eq 0 ] && sudo= || sudo="sudo "

#function 
function public_linux_alias()
{
	case $OSTYPE in
		linux-gnu)
			alias sync="${sudo}sync;${sudo}sync;${sudo}sync;${sudo}sync"
			[ -e /dev/disk/by-label/Applications ] && [ -d "/media/Applications" ] && type mount-app &>/dev/null || alias mount-app="${sudo}mount -vw -t ntfs /dev/disk/by-label/Applications /media/Applications" 
			[ -d "/media/tmp" ] && type umt &>/dev/null || alias umt="${sudo}umount -v /media/tmp"
			[ -d "/media/Applications" ] && type uma &>/dev/null || alias uma="${sudo}umount -v /media/Applications"
			[ -d "/media/Others" ] && type umo &>/dev/null || alias umo="${sudo}umount -v /media/Others"
			type cs &> /dev/null || alias cs="${sudo}sync;${sudo}sync;${sudo}sync;${sudo}shutdown -hf now"
			type rs &>/dev/null || alias rs="${sudo}sync;${sudo}sync;${sudo}sync; ${sudo}reboot now"
			if [ "$TERM" == "linux" ] && ps aux|grep -v grep|grep fbterm &>/dev/null;then 
				alias vim="TERM=fbterm vim";
				type sudoe &>/dev/null || alias sudoe="TERM=fbterm ${sudo}-E vim"
			else 
				type sudoe &>/dev/null || alias sudoe="${sudo}-E vim"
        [ $EUID -eq 0 ] && unalias sudoe &>/dev/null
			fi
			[ -x /usr/bin/notify-send ] && type alert &>/dev/null || alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
      alias cknet="echo 'Checking the networks......';ping -c2 www.baidu.com &>/dev/null&&echo Network is OK.||echo Network is not working.";;
	esac
}

####### function public_alias All Like Linux OS #######
function public_alias()
{
  public_linux_alias
  type -a .. &> /dev/null || alias ..="cd .."
  type -a ... &> /dev/null || alias ...="cd ../.."
	type -a md &> /dev/null || alias md="mkdir -pv" 
	alias free="free -hmt"
	alias ls="ls --color=auto"
  alias ll="ls -aSFlh --color=always"
	type -a l >& /dev/null || alias l="ls -AF --color=always"
	#type -a la >& /dev/null || alias la="ls -AF --color=always"
  alias dir="dir --color=always"
	alias dirs="dirs -v"
  alias vdir="vdir --color=auto"
  alias grep="grep -E --color=auto"
  alias fgrep="fgrep --color=auto"
  alias egrep="egrep --color=auto"
  alias pwd="pwd -P"
  [[ $TERM == "linux" || $TERM == "screen" || $TERM == "fbterm" ]] && alias cd="cd -P"
  alias du="du -h"
  alias df="df -h"
  alias cp="cp -iv"
  alias rm="rm -iv"
  alias mv="mv -iv"
  alias less="less -R"
	alias pushd="pushd $1 &> /dev/null"
	alias popd="popd $1 &> /dev/null"
	type sed_expand_tab >& /dev/null || alias sed_expand_tab="sed 's/\t/  /g'"
}

###
function other_alias()
{
	case $OS in
		Arch*)
			type update-grub &>/dev/null || alias update-grub="${sudo}grub-mkconfig -o /boot/efi/EFI/Arch/grub/grub.cfg";;
		Ubuntu*|Fedora*)
			type sl &> /dev/null || alias sl="skill -u ";;
	esac
}

####### function pacman_alias 
function pacman_alias()
{
	type pacs &>/dev/null || alias pacs="pacman -Ss"
	type pacq &>/dev/null || alias pacq="pacman -Q"
	type pacf &>/dev/null || alias pacf="pacman -F"
	type pacfs &>/dev/null || alias pacfs="pacman -Fs"
	case $OS in
		Arch*|Fedo*)
			type paci &>/dev/null || alias paci="${sudo}pacman -S --needed "
			type pacr &>/dev/null || alias pacr="${sudo}pacman -Rn"
			type pacu &>/dev/null || alias pacu="${sudo}pacman -Syyu"
			type pacfu &> /dev/null || alias pacfu="${sudo}pacman -Fy";;
		msys)
			type pacu &> /dev/null || alias pacu="pacman -Syyu"
			type paci &> /dev/null || alias paci="pacman -S --needed"
			type pacfu &> /dev/null || alias pacfu="pacman -Fy"
			type pacr &> /dev/null || alias pacr="pacman -Rn";;
	esac
}

########## package alias function ##########
function package_manage()
{
	case $OS in
		Arch*)
			pacman_alias;;
		Cent*)
			:;;
		Fedora*)
			pacman_alias
			type dnfi &>/dev/null || alias dnfi="${sudo}dnf install"
			type dnfs &>/dev/null || alias dnfs="dnf search"
			type dnfr &>/dev/null || alias dnfr="${sudo}dnf remove"
			type dnfu &>/dev/null || alias dnfu="${sudo}dnf update";;
		Gentoo*)
      type emeri &>/dev/null || alias emeri="${sudo}emerge --ask"
      type emers &>/dev/null || alias emers="emerge --search"
			;;
		Ubuntu*)
			type apti &>/dev/null || alias apti="${sudo}apt-get install"
			type aptr &>/dev/null || alias apti="${sudo}apt-get install"
			type apts &>/dev/null || alias apti="${sudo}apt-get install";;
		OpenSUSE*)
			:;;
		msys)
			pacman_alias;;
	esac
}
##

other_alias
public_alias
package_manage
#
unset -f other_alias package_manage pacman_alias public_linux_alias public_alias
